export default {
  'sonarjs/cognitive-complexity': [1, 30],
  'sonarjs/elseif-without-else': 0,
  'sonarjs/max-switch-cases': [1, 40],
  'sonarjs/no-all-duplicated-branches': 1,
  'sonarjs/no-collapsible-if': 1,
  'sonarjs/no-collection-size-mischeck': 1,
  'sonarjs/no-duplicate-string': 1,
  'sonarjs/no-duplicated-branches': 1,
  'sonarjs/no-element-overwrite': 1,
  'sonarjs/no-empty-collection': 1,
  'sonarjs/no-extra-arguments': 1,
  'sonarjs/no-gratuitous-expressions': 1,
  'sonarjs/no-identical-conditions': 1,
  'sonarjs/no-identical-expressions': 1,
  'sonarjs/no-identical-functions': 1,
  'sonarjs/no-ignored-return': 1,
  'sonarjs/no-inverted-boolean-check': 1,
  'sonarjs/no-nested-switch': 1,
  'sonarjs/no-nested-template-literals': 0,
  'sonarjs/no-redundant-boolean': 1,
  'sonarjs/no-redundant-jump': 1,
  'sonarjs/no-same-line-conditional': 1,
  'sonarjs/no-small-switch': 1,
  'sonarjs/no-unused-collection': 1,
  'sonarjs/no-use-of-empty-return-value': 1,
  'sonarjs/no-useless-catch': 1,
  'sonarjs/non-existent-operator': 1,
  'sonarjs/prefer-immediate-return': 1,
  'sonarjs/prefer-object-literal': 1,
  'sonarjs/prefer-single-boolean-return': 1,
  'sonarjs/prefer-while': 1,
}
