volumes:
  budget_app_keycloak_import:

services:
  keycloak:
    container_name: keycloak
    image: "keycloak-curl-budget-app:latest"
    volumes:
      - budget_app_keycloak_import:/opt/keycloak/data/import
      - ./backup/budget-app-realm.json:/opt/keycloak/data/import/budget-app-realm.json
    command: start --optimized --import-realm
    ports:
      - "8080:8080"